name: commit stage
on: [push, workflow_dispatch]
jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'gradle'
      - name: Code vulnerability scanning with Anchore Grype
        uses: anchore/scan-action@v3.6.4
        id: scan #identifier for subsequent steps to use (line 31)
        with:
          path: "${{ github.workspace }}"  # path to the checked-out repository                
          fail-build: false                                
          severity-cutoff: high # The minimum security category to be considered as an error (low, medium, high, critical)                            
      - name: upload vulnerability scanning report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure() # to still upload report even on failure
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests 
        run: | 
          chmod +x gradlew                                 
          ./gradlew build 
        
        
